# Generated by Django 4.1.3 on 2022-12-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubdomainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain_name', models.CharField(max_length=255)),
                ('cname', models.CharField(max_length=255)),
                ('webserver', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=255)),
                ('status_code', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('tech_stack_detect', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('content_length', models.IntegerField()),
                ('ipv6', models.CharField(max_length=255)),
                ('ports', models.CharField(max_length=255)),
                ('screenshot_path', models.CharField(max_length=255)),
                ('domain_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subdomain_app.domainsearchhistory')),
            ],
        ),
    ]
