# Generated by Django 4.1.3 on 2022-12-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdomain_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomaindetails',
            name='content_length',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subdomaindetails',
            name='response_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subdomaindetails',
            name='status_code',
            field=models.CharField(max_length=255),
        ),
    ]
