# Generated by Django 4.1.3 on 2022-12-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdomain_app', '0002_alter_subdomaindetails_content_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainsearchhistory',
            name='domain_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
